Sprint 6
wolfie-game/wolfie pull request #5
Opened 2022-01-25 19:21 UTC by iamkirabond

2022-01-30 13:06 UTC, ivan-infro commented on src/components/Canvas/Canvas.tsx
>      const draw = () => {
Метод draw пора разделить на отдельные файлы, а то Canvas.tsx станет слишком толстым

2022-01-30 13:06 UTC, ivan-infro commented on src/components/Pages/Main/Main.tsx
> +      <div className="content__canvas" id="canvas">
Вместо id лучше добавить ref https://ru.reactjs.org/docs/refs-and-the-dom.html

2022-02-01 14:35 UTC, iamkirabond commented on src/components/Canvas/Canvas.tsx
>      const draw = () => {
теперь все элементы на канвасе вынесены в отдельные классы

2022-02-03 15:15 UTC, ivan-infro requested changes

2022-02-03 15:15 UTC, ivan-infro commented on package.json
> +    "@types/redux": "^3.6.0",
Можно удалить, потому что redux поставляется вместе с типами, а в этом пакете файлов нету

2022-02-03 15:15 UTC, ivan-infro commented on src/utils/redux/store.ts
> +import {rootSaga} from '../sagas'
rootSaga импортируется, но нигде не используется

2022-02-03 15:15 UTC, ivan-infro commented on src/utils/redux/store.ts
>  import {createStore, applyMiddleware} from 'redux'
import {composeWithDevTools} from 'redux-devtools-extension'

2022-02-03 15:15 UTC, ivan-infro commented on src/utils/redux/store.ts
> +  const store = createStore(reducers, applyMiddleware(sagaMiddleware))
const store = createStore(
    reducers,
    composeWithDevTools(applyMiddleware(sagaMiddleware)),
  )

2022-02-06 10:44 UTC, ivan-infro commented
Регулярка` /^([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?$/,` не пропускает валидный адрес mail@example.games, потому что в домене 1го уровня больше 4х символов.

На эту тему есть несколько статей, например, [Я знал, как валидировать email-адрес. Пока не прочитал RFC](https://habr.com/en/post/274985/), [Прекратите проверять Email с помощью регулярных выражений!](https://habr.com/en/post/175375/) и другие

Если кратко: в email стоит проверять, пожалуй, только наличие "@"

2022-02-06 11:11 UTC, ivan-infro requested changes

2022-02-06 11:11 UTC, ivan-infro commented on src/utils/redux/store.ts
> +export const initialState: UserState = {
Переменная экспортируется из модуля, но нигде не используется, поэтому ее можно удалить
ESLint ее не помечает как неиспользуемую из-за наличия экспорта

2022-02-06 11:11 UTC, ivan-infro commented on src/utils/redux/reducers/index.ts
> +  userReducer,
FYI: Обратите внимание, что из объекта, переданного в combineReducers, redux создает состояние стора:
![image](https://user-images.githubusercontent.com/5419627/152677502-47b23a06-5a38-438a-bb24-3ec24b2be404.png)

Постфикс "Reducer" тут можно удалить

2022-02-06 11:12 UTC, ivan-infro commented
Если отключить интернет и обновить страницу, то игра не открывается (должна открываться из кеша Service Worker)

2022-02-13 09:23 UTC, merged